variables:

  ######################################
  # Agent settings
  ######################################

  vmImage: 'ubuntu-latest' # Use this for Microsoft-hosted agents
  poolName: '' # Use this for self-hosted agents
